import type { Opening } from './types';

export const BLACK_OPENINGS: Opening[] = [
  {
    id: 'sicilian-najdorf',
    name: 'Sicilian Defence: Najdorf',
    eco: 'B90',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be3', 'e5', 'Nb3', 'Be6', 'f3', 'Be7'],
    difficulty: 3,
    style: ['sharp', 'ambitious', 'theory-heavy'],
    summary:
      'The most analysed opening in chess history, and the choice of Fischer and Kasparov. The modest ...a6 controls b5 and keeps every option open. You play for a win with Black — and you pay for it in study hours.',
    ideas: [
      '...a6 stops both Nb5 and Bb5, so Black can arrange ...e5 or ...e6 on his own terms.',
      'After ...e5 the d5 square is weak, but Black gets the e5 wedge and fast piece play in return.',
      'Black\'s counterplay is nearly always on the queenside: ...b5, ...Nbd7-b6, ...Rc8 and pressure on c4/c3.',
      'Know which system you face on move six: 6.Be3 (English Attack), 6.Bg5 (main line), 6.Be2 (Classical), 6.f4, 6.g3, 6.h3.',
    ],
    plans: {
      you: [
        'Expand with ...b5 and put a knight on c4 or b6.',
        'Control d5 with ...Be6, ...Nbd7 and sometimes ...Rc8 before White can plant a piece there.',
        'If White castles long and storms with g4-g5, meet it with ...b5-b4 and open the c-file fast.',
      ],
      them: [
        'White plays Be3, f3, Qd2 and g4 for a direct kingside pawn storm.',
        'Nd5 is the dream square — White will fight hard to occupy it.',
        'Bg5 pressures f6 and tries to force structural concessions.',
      ],
    },
    steps: [
      { upto: 2, title: '1.e4 c5 — the Sicilian', body: 'Black declines symmetry. Trading a flank pawn for a centre pawn gives Black the half-open c-file and the best practical winning chances against 1.e4.' },
      { upto: 6, title: '2.Nf3 d6 3.d4 cxd4', body: 'Black takes, entering the Open Sicilian. White gets a lead in development; Black gets the c-file and a healthy extra centre pawn.' },
      { upto: 10, title: '4.Nxd4 Nf6 5.Nc3 a6 — the Najdorf move', body: '...a6 looks slow but it is prophylaxis: no white piece will ever use b5. Only now does Black decide between ...e5 and ...e6.' },
      { upto: 12, title: '6.Be3 e5 — the English Attack', body: 'Black grabs the centre and kicks the knight. Yes, d5 becomes a hole — but White needs several moves to exploit it, and Black is faster.' },
      { upto: 16, title: '7.Nb3 Be6 8.f3 Be7', body: 'Be6 guards d5 immediately. White prepares g4; Black prepares ...Nbd7, ...O-O and ...b5. Both sides race on opposite wings.' },
    ],
    branches: [
      { name: 'Najdorf, 6.Bg5 (main line)', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Bg5', 'e6', 'f4', 'Be7'], idea: 'The classical main line. Black plays ...e6 here rather than ...e5, keeping a solid structure. The Poisoned Pawn (6...e6 7.f4 Qb6) is the wildest branch in all of chess.' },
      { name: 'Najdorf, 6.Be2 (Classical)', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be2', 'e5', 'Nb3', 'Be7'], idea: 'A calm, high-quality system. Black gets ...e5 in comfortably and the game is a genuine positional fight.' },
      { name: 'Scheveningen structure', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'a6', 'Be2', 'e6'], idea: 'The "small centre" with pawns on d6 and e6. Extremely solid and flexible — many Najdorf players transpose here on purpose.' },
    ],
    traps: [],
  },
  {
    id: 'sicilian-dragon',
    name: 'Sicilian Defence: Dragon',
    eco: 'B70',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Be3', 'Bg7', 'f3', 'O-O', 'Qd2', 'Nc6'],
    difficulty: 3,
    style: ['sharp', 'attacking', 'double-edged'],
    summary:
      'Fianchetto the bishop on the long diagonal and race. In the Yugoslav Attack both sides castle on opposite wings and throw everything at the enemy king — the sharpest mainstream opening there is.',
    ideas: [
      'The g7-bishop is the whole point: it looks straight down the a1-h8 diagonal at White\'s queenside.',
      'The exchange sacrifice ...Rxc3! is a defining Dragon idea — it removes the defender of White\'s king and opens the long diagonal.',
      'Speed decides everything. Count tempi, not material.',
      'Against the quiet 6.Be2 (Classical Dragon), Black gets a normal, pleasant game with ...Nc6 and ...Bg4.',
    ],
    plans: { you: ['Play ...Rc8, ...Ne5 and ...Rxc3 at the right moment.', 'Advance ...b5-b4 to open lines toward the white king.', 'Keep the g7-bishop alive at almost any cost.'], them: ['Castle long, then storm with h4-h5 and g4.', 'Trade off the g7-bishop with Be3-h6.', 'Land a knight or bishop on d5.'] },
    steps: [
      { upto: 8, title: '1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6', body: 'The Open Sicilian. So far identical to the Najdorf.' },
      { upto: 10, title: '5.Nc3 g6 — the Dragon', body: 'Instead of ...a6 or ...e6, Black fianchettoes. The bishop will be the most important piece on the board.' },
      { upto: 12, title: '6.Be3 Bg7', body: 'White heads for the Yugoslav Attack: f3, Qd2, O-O-O and h4-h5. Black completes the fianchetto and prepares to castle into the storm.' },
      { upto: 16, title: '7.f3 O-O 8.Qd2 Nc6', body: 'Both plans are now fully declared. Black continues ...Bd7, ...Rc8, ...Ne5 and looks for ...Rxc3. This is a race — play fast, forcing moves.' },
    ],
    branches: [
      { name: 'Yugoslav Attack, 9.Bc4', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Be3', 'Bg7', 'f3', 'O-O', 'Qd2', 'Nc6', 'Bc4'], idea: 'The critical test. Black answers ...Bd7 and ...Rc8, preparing ...Ne5 and the exchange sacrifice on c3.' },
      { name: 'Classical Dragon', moves: ['e4', 'c5', 'Nf3', 'd6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'g6', 'Be2', 'Bg7', 'O-O', 'O-O'], idea: 'White castles short instead. Much calmer; Black gets easy play with ...Nc6, ...Bd7 and ...Rc8.' },
      { name: 'Accelerated Dragon', moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'g6', 'c4', 'Bg7', 'Be3', 'Nf6', 'Nc3', 'O-O'], idea: 'Delay ...d6 so that ...d5 becomes possible in one go, dodging the Yugoslav Attack entirely. The price is facing the Maróczy Bind with c4.' },
    ],
    traps: [],
  },
  {
    id: 'sicilian-sveshnikov',
    name: 'Sicilian Defence: Sveshnikov',
    eco: 'B33',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5', 'Ndb5', 'd6', 'Bg5', 'a6', 'Na3', 'b5'],
    difficulty: 3,
    style: ['sharp', 'unbalanced'],
    summary:
      'Black voluntarily accepts a hole on d5 and often a doubled f-pawn, in exchange for enormous piece activity and the two bishops. Used by Kramnik and Carlsen at the very top.',
    ideas: [
      'The d5 hole is real, but Black covers it with pieces and gets the initiative everywhere else.',
      '...b5 gains queenside space and prepares to trap the knight on a3 out of play.',
      'After Bxf6 gxf6 Black has doubled f-pawns but two bishops, the g-file, and a strong e5/f5 pawn duo.',
      'Very concrete: learn the first twelve moves properly or do not play it.',
    ],
    plans: { you: ['Expand with ...b5, ...Rb8 and ...b4 to push the a3-knight further offside.', 'Open the g-file after Bxf6 gxf6 and attack.', 'Use the two bishops in the resulting semi-open positions.'], them: ['Occupy d5 with a knight and keep it there.', 'Trade the dark-squared bishop for the f6-knight to weaken Black\'s structure.', 'Play c4 to fix the queenside and blunt Black\'s expansion.'] },
    steps: [
      { upto: 8, title: '1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 Nf6', body: 'The Sicilian with ...Nc6 first, keeping ...e5 available in one move.' },
      { upto: 10, title: '5.Nc3 e5! — the Sveshnikov', body: 'A shocking move by classical standards: it permanently weakens d5. But the knight on d4 is kicked and Black seizes the initiative.' },
      { upto: 12, title: '6.Ndb5 d6', body: 'The knight jumps to b5 hitting d6 and c7. Black just defends.' },
      { upto: 16, title: '7.Bg5 a6 8.Na3 b5', body: 'The knight is driven to a3 where it sits offside for a long time. Black already has queenside momentum — this is the point of the whole line.' },
    ],
    branches: [
      { name: 'Sveshnikov, 9.Bxf6 gxf6', moves: ['e4', 'c5', 'Nf3', 'Nc6', 'd4', 'cxd4', 'Nxd4', 'Nf6', 'Nc3', 'e5', 'Ndb5', 'd6', 'Bg5', 'a6', 'Na3', 'b5', 'Bxf6', 'gxf6'], idea: 'The main line. Doubled f-pawns for the two bishops and the g-file — a trade-off Black is happy to make.' },
      { name: 'Rossolimo (3.Bb5)', moves: ['e4', 'c5', 'Nf3', 'Nc6', 'Bb5'], idea: 'White sidesteps the whole Open Sicilian. Answer ...g6 or ...e6 and expect a positional game rather than a theoretical battle.' },
    ],
    traps: [],
  },
  {
    id: 'french',
    name: 'French Defence: Winawer',
    eco: 'C18',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Bb4', 'e5', 'c5', 'a3', 'Bxc3+', 'bxc3', 'Ne7', 'Qg4', 'O-O'],
    difficulty: 3,
    style: ['unbalanced', 'strategic'],
    summary:
      'Solid but fighting. Black concedes space and the light-squared bishop\'s freedom, then attacks the base of White\'s pawn chain on d4. The Winawer is the sharpest version and gives White real problems.',
    ideas: [
      'The French pawn chain (d4-e5 vs d5-e6) defines everything: Black attacks its base with ...c5, White defends it.',
      'The c8-bishop is the "French bishop" — Black\'s standard problem piece. Plan for it from move one with ...b6 and ...Ba6, or ...Bd7-a4.',
      'In the Winawer, Black trades the dark-squared bishop for structural damage to White\'s queenside (doubled c-pawns).',
      'Do not fear ...O-O against Qg4. The g7 pawn is defensible and White\'s queen is loose.',
    ],
    plans: { you: ['Pressure d4 with ...c5, ...Nc6 and ...Qb6.', 'Target the doubled c-pawns in an endgame.', 'Solve the c8-bishop: ...b6 and ...Ba6, or ...Bd7 and ...Bb5.'], them: ['Hold the chain with c3 and f4, then attack on the kingside.', 'Use the extra space to manoeuvre freely.', 'Play Qg4 and Bd3 aiming at h7 and g7.'] },
    steps: [
      { upto: 4, title: '1.e4 e6 2.d4 d5', body: 'Black challenges the centre immediately. White must decide: advance (3.e5), exchange (3.exd5), or develop (3.Nc3 / 3.Nd2).' },
      { upto: 6, title: '3.Nc3 Bb4! — the Winawer', body: 'Black pins the knight and attacks e4 a second time. The most ambitious answer to 3.Nc3.' },
      { upto: 8, title: '4.e5 c5', body: 'White pushes past and gains space. Black immediately hits the base of the chain.' },
      { upto: 12, title: '5.a3 Bxc3+ 6.bxc3 Ne7', body: 'White forces the trade; Black damages White\'s structure. Those doubled c-pawns will matter for the rest of the game.' },
      { upto: 14, title: '7.Qg4 O-O', body: 'White grabs at g7; Black calmly castles into it. The rook on f8 defends, and White\'s queen will have to retreat eventually.' },
    ],
    branches: [
      { name: 'French Classical', moves: ['e4', 'e6', 'd4', 'd5', 'Nc3', 'Nf6', 'e5', 'Nfd7', 'f4', 'c5'], idea: 'A calmer answer to 3.Nc3: solid, strategic, less theory than the Winawer, with the same ...c5 plan.' },
      { name: 'French Tarrasch (3.Nd2)', moves: ['e4', 'e6', 'd4', 'd5', 'Nd2', 'c5', 'exd5', 'Qxd5', 'Ngf3', 'cxd4'], idea: 'White avoids the Winawer pin. Black gets an open, comfortable game with ...c5 and quick development.' },
      { name: 'Advance Variation', moves: ['e4', 'e6', 'd4', 'd5', 'e5', 'c5', 'c3', 'Nc6', 'Nf3', 'Qb6'], idea: 'The most common line at club level. Black attacks d4 three times with ...c5, ...Nc6 and ...Qb6 — a clear, repeatable plan.' },
      { name: 'Exchange Variation', moves: ['e4', 'e6', 'd4', 'd5', 'exd5', 'exd5'], idea: 'Symmetrical and drawish-looking, but Black\'s bishop is finally free. Play ...Nf6, ...Bd6, ...O-O and aim for a slow build-up.' },
    ],
    traps: [],
  },
  {
    id: 'caro-kann',
    name: 'Caro-Kann Defence: Classical',
    eco: 'B18',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Bf5', 'Ng3', 'Bg6', 'h4', 'h6', 'Nf3', 'Nd7', 'h5', 'Bh7', 'Bd3', 'Bxd3', 'Qxd3', 'e6'],
    difficulty: 2,
    style: ['solid', 'positional', 'low-risk'],
    summary:
      'The French Defence without the bad bishop. Black supports ...d5 with the c-pawn, so the light-squared bishop gets out first. Extremely sound — the best choice if you hate being attacked.',
    ideas: [
      'Playing ...c6 before ...d5 means the c8-bishop is never trapped. That single difference from the French is the entire appeal.',
      'Black usually ends up with a healthy pawn structure and no weaknesses, at the cost of a little space.',
      'The h4-h5 push traps the bishop on h7 but costs White time and loosens the kingside.',
      'Know the Advance Variation (3.e5) — it is the most common line you will actually face.',
    ],
    plans: { you: ['Develop ...Nd7, ...Ngf6, ...e6, ...Bd6 and castle. No weaknesses, no problems.', 'Play ...c5 at the right moment to open the position.', 'Aim for an endgame — your structure is usually the better one.'], them: ['Gain space with h4-h5 and a big centre.', 'Play c4 to build a broad pawn front.', 'Exploit the small space advantage with piece manoeuvres.'] },
    steps: [
      { upto: 4, title: '1.e4 c6 2.d4 d5', body: 'Black prepares ...d5 with a pawn rather than a piece, so d5 is properly supported.' },
      { upto: 8, title: '3.Nc3 dxe4 4.Nxe4 Bf5!', body: 'The Classical Variation. Black develops the "problem" bishop to an excellent square before playing ...e6. This is the whole idea of the Caro-Kann.' },
      { upto: 12, title: '5.Ng3 Bg6 6.h4 h6', body: 'White harasses the bishop. ...h6 is essential — it gives the bishop the h7 square and prevents Nh5 tricks.' },
      { upto: 16, title: '7.Nf3 Nd7 8.h5 Bh7', body: 'The bishop looks passive on h7, but it is safe, and White has committed pawns on the kingside that may become weaknesses.' },
      { upto: 20, title: '9.Bd3 Bxd3 10.Qxd3 e6', body: 'Black trades off the bishop on his own terms and builds a solid, flexible position. Next: ...Ngf6, ...Bd6 or ...Be7, ...Qc7 and castle.' },
    ],
    branches: [
      { name: 'Advance Variation', moves: ['e4', 'c6', 'd4', 'd5', 'e5', 'Bf5', 'Nf3', 'e6', 'Be2', 'c5'], idea: 'The most common practical line. Get the bishop out to f5 first, then hit the centre with ...c5.' },
      { name: 'Exchange Variation', moves: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'Bd3', 'Nc6', 'c3', 'Nf6'], idea: 'Simple and symmetrical. Develop naturally; the position is balanced and easy to play.' },
      { name: 'Panov-Botvinnik Attack', moves: ['e4', 'c6', 'd4', 'd5', 'exd5', 'cxd5', 'c4', 'Nf6', 'Nc3', 'e6'], idea: 'White goes for an isolated-queen\'s-pawn position with active pieces. Black should blockade d5 and trade pieces.' },
      { name: 'Karpov Variation (4...Nd7)', moves: ['e4', 'c6', 'd4', 'd5', 'Nc3', 'dxe4', 'Nxe4', 'Nd7'], idea: 'Ultra-solid: Black avoids any structural damage from Nxf6 by preparing ...Ngf6 first. Karpov\'s choice, and nearly impossible to crack.' },
    ],
    traps: [],
  },
  {
    id: 'scandinavian',
    name: 'Scandinavian Defence',
    eco: 'B01',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'd5', 'exd5', 'Qxd5', 'Nc3', 'Qa5', 'd4', 'Nf6', 'Nf3', 'c6', 'Bc4', 'Bf5'],
    difficulty: 1,
    style: ['direct', 'low-theory'],
    summary:
      'Challenge e4 on move one and trade it off immediately. You get a clear structure and a tiny amount of theory to learn — the fastest way to a playable Black repertoire.',
    ideas: [
      'The queen comes out early but is not really in danger: after ...Qa5 it sits on a safe diagonal.',
      'Black has no bad bishop and no cramped pieces, unlike the French.',
      'The cost is a tempo or two, which White converts into space. Accept it and play solidly.',
      'The Modern Scandinavian (2...Nf6) is a respectable alternative if you dislike early queen moves.',
    ],
    plans: { you: ['Develop with ...Nf6, ...c6, ...Bf5 and ...e6 — a clean, repeatable setup.', 'Castle and put a rook on d8 to pressure d4.', 'Play ...Nbd7 and ...Bb4 or ...Be7 depending on White\'s setup.'], them: ['Gain time by attacking the black queen.', 'Build a big centre with d4 and c4.', 'Play Bd2 and Nd5 to harass the queen on a5.'] },
    steps: [
      { upto: 2, title: '1.e4 d5', body: 'The most direct challenge to 1.e4. White almost always takes.' },
      { upto: 4, title: '2.exd5 Qxd5', body: 'Recapturing with the queen is the classical choice. It looks risky but the queen has a safe retreat.' },
      { upto: 6, title: '3.Nc3 Qa5', body: 'White gains a tempo; Black steps to a5 where the queen is awkward to attack again. ...Qd6 and ...Qd8 are also fully playable.' },
      { upto: 12, title: '4.d4 Nf6 5.Nf3 c6 6.Bc4 Bf5', body: 'Black develops naturally, supports d5-square control with ...c6, and gets the light-squared bishop out. Next: ...e6, ...Nbd7 and castle.' },
    ],
    branches: [
      { name: 'Modern Scandinavian', moves: ['e4', 'd5', 'exd5', 'Nf6'], idea: 'Recapture with the knight instead. After 3.d4 Nxd5 4.c4 Nb6 Black has a slightly cramped but sound game with no early queen exposure.' },
      { name: 'Icelandic Gambit', moves: ['e4', 'd5', 'exd5', 'Nf6', 'c4', 'e6'], idea: 'A genuine pawn sacrifice for rapid development and open lines. Fun, and surprisingly sound.' },
    ],
    traps: [],
  },
  {
    id: 'petrov',
    name: 'Petrov Defence',
    eco: 'C42',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4', 'd4', 'd5', 'Bd3', 'Be7', 'O-O', 'Nc6'],
    difficulty: 2,
    style: ['symmetrical', 'solid', 'drawish'],
    summary:
      'Also called the Russian Defence. Instead of defending e5, Black copies White and attacks e4. Symmetry leads to an extremely sound position — a favourite of players who are happy with a draw as Black.',
    ideas: [
      'Do not play 3...Nxe4 immediately: 4.Qe2! wins material after the discovered attack. Insert 3...d6 first.',
      'The resulting structures are symmetrical, so understanding matters more than memorisation.',
      'Black\'s pieces all have natural squares: ...Be7, ...O-O, ...Nc6, ...Bf5 or ...Bg4.',
      'White\'s main try for an edge is the sharp 5.Nc3 (instead of 5.d4), inviting complications.',
    ],
    plans: { you: ['Complete the mirror setup and castle.', 'Put a rook on e8 and pressure the e-file.', 'Trade pieces to reach a comfortable, balanced endgame.'], them: ['Play c4 to challenge d5 and unbalance the position.', 'Use Re1 and the e-file first.', 'Try Nc3 lines to create asymmetry while there is still material on the board.'] },
    steps: [
      { upto: 4, title: '1.e4 e5 2.Nf3 Nf6', body: 'Rather than defending e5 with ...Nc6, Black counterattacks e4. A pure symmetry play.' },
      { upto: 6, title: '3.Nxe5 d6!', body: 'The essential move order. Taking at once with 3...Nxe4?? loses to 4.Qe2 Qe7 5.Qxe4 — the knight on e5 unveils a discovered attack. ...d6 kicks first.' },
      { upto: 8, title: '4.Nf3 Nxe4', body: 'Now Black recovers the pawn safely and the position is symmetrical again.' },
      { upto: 14, title: '5.d4 d5 6.Bd3 Be7 7.O-O Nc6', body: 'A textbook symmetrical structure. Black is solid, has no weaknesses, and every piece has a job.' },
    ],
    branches: [
      { name: 'Petrov, sharp 5.Nc3', moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nxe5', 'd6', 'Nf3', 'Nxe4', 'Nc3', 'Nxc3', 'dxc3'], idea: 'White accepts a slightly worse structure for open lines and fast development. Black should castle quickly and stay alert.' },
      { name: 'Four Knights', moves: ['e4', 'e5', 'Nf3', 'Nf6', 'Nc3', 'Nc6'], idea: 'White declines the trade. A calm, classical game where Black is entirely comfortable.' },
    ],
    traps: [],
  },
  {
    id: 'pirc',
    name: 'Pirc Defence',
    eco: 'B07',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O', 'O-O', 'c6'],
    difficulty: 2,
    style: ['hypermodern', 'counterattacking'],
    summary:
      'Let White build a big centre, then knock it down. Black develops fast, castles, and hits back with ...c5 or ...e5. Flexible, fighting, and it avoids the huge theory of 1.e4 e5 and the Sicilian.',
    ideas: [
      'Hypermodern idea: a large pawn centre becomes a liability if you can attack it before it becomes a steamroller.',
      'The g7-bishop and a timely ...e5 or ...c5 are Black\'s two core resources.',
      'Beware the Austrian Attack (4.f4) — White\'s most aggressive setup, and the line you must know best.',
      'Never delay castling in the Pirc. Getting the king safe is what makes the counterattack possible.',
    ],
    plans: { you: ['Castle, then break with ...c5 or ...e5 depending on White\'s setup.', 'Play ...Nbd7, ...b5 and ...Bb7 for queenside play.', 'Keep the g7-bishop and aim it at d4 and b2.'], them: ['Build the centre with e4, d4 and f4, then push e5.', 'Attack with Be3, Qd2, h4 and Bh6 to trade the fianchettoed bishop.', 'Play Bc4 and Qe2 with pressure on f7.'] },
    steps: [
      { upto: 4, title: '1.e4 d6 2.d4 Nf6', body: 'Black invites White to occupy the centre while developing quickly and flexibly.' },
      { upto: 6, title: '3.Nc3 g6', body: 'The fianchetto. The bishop on g7 will pressure d4 for the whole game.' },
      { upto: 10, title: '4.Nf3 Bg7 5.Be2 O-O', body: 'The Classical System — White develops calmly. Black castles immediately, which is always the priority.' },
      { upto: 12, title: '6.O-O c6', body: 'Preparing ...b5 and ...Qc7 with queenside expansion, or ...e5 in the centre. Black has a sound position with clear plans.' },
    ],
    branches: [
      { name: 'Austrian Attack', moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'f4', 'Bg7', 'Nf3', 'c5'], idea: 'White\'s most dangerous try. Strike back at once with ...c5 — passive play here gets crushed.' },
      { name: '150 Attack', moves: ['e4', 'd6', 'd4', 'Nf6', 'Nc3', 'g6', 'Be3', 'Bg7', 'Qd2', 'c6', 'f3'], idea: 'A straightforward plan of Be3, Qd2, O-O-O and h4-h5. Meet it with ...b5 and fast queenside counterplay.' },
      { name: 'Modern Defence', moves: ['e4', 'g6', 'd4', 'Bg7', 'Nc3', 'd6'], idea: 'The same ideas with a different move order, delaying ...Nf6 to keep more options (and dodge some Austrian Attack lines).' },
    ],
    traps: [],
  },
  {
    id: 'alekhine',
    name: "Alekhine's Defence",
    eco: 'B04',
    side: 'b',
    group: 'vs-e4',
    moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'Nf3', 'dxe5', 'Nxe5', 'c6'],
    difficulty: 2,
    style: ['provocative', 'hypermodern'],
    summary:
      'Provoke White into overextending. The knight invites pawn kicks, and every pawn White pushes is one more pawn Black can attack later. Rare, offbeat, and it takes opponents out of their preparation instantly.',
    ideas: [
      'Black deliberately loses time to lure White\'s pawns forward. Those pawns become targets.',
      'The Four Pawns Attack (4.c4 Nb6 5.f4) is the ultimate test — know it or avoid the opening.',
      'Black aims for ...c6, ...Bf5 or ...g6, then chips at the centre with ...dxe5 and ...c5.',
      'Because it is rare, most opponents will play natural moves and end up overextended.',
    ],
    plans: { you: ['Trade off White\'s advanced pawns with ...dxe5 and ...c5.', 'Develop the light-squared bishop actively to f5 or g4.', 'Target d4 and e5 with pieces once the pawns are gone.'], them: ['Gain space and keep kicking the knight.', 'Play c4 and f4 for a huge pawn front.', 'Punish Black\'s lost tempi with quick development.'] },
    steps: [
      { upto: 2, title: '1.e4 Nf6!?', body: 'Immediately attacking e4 with a piece rather than a pawn. White almost always pushes past.' },
      { upto: 4, title: '2.e5 Nd5', body: 'The knight retreats to the centre. It will be kicked again, and that is fine — each kick commits another white pawn.' },
      { upto: 6, title: '3.d4 d6 — the Modern Variation', body: 'Black immediately questions the e5 pawn. This is the soundest system in the whole opening.' },
      { upto: 10, title: '4.Nf3 dxe5 5.Nxe5 c6', body: 'The advanced pawn is gone and Black has a compact, flexible position. Next: ...Bf5 or ...g6, ...Nd7 and castle.' },
    ],
    branches: [
      { name: 'Four Pawns Attack', moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'c4', 'Nb6', 'f4'], idea: 'White builds an enormous centre. Black must hit it immediately with ...dxe5 and ...Bf5, or get rolled.' },
      { name: 'Exchange Variation', moves: ['e4', 'Nf6', 'e5', 'Nd5', 'd4', 'd6', 'Nf3', 'dxe5', 'dxe5'], idea: 'A quieter recapture. Black plays ...Nc6 and ...Bf5 with a comfortable, balanced game.' },
    ],
    traps: [],
  },
  {
    id: 'nimzo-indian',
    name: 'Nimzo-Indian Defence',
    eco: 'E32',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'Qc2', 'O-O', 'a3', 'Bxc3+', 'Qxc3', 'b6'],
    difficulty: 2,
    style: ['positional', 'strategic', 'respected'],
    summary:
      'The most respected answer to 1.d4. Black pins the c3-knight to stop e4, and is willing to trade bishop for knight in order to damage White\'s structure or win control of the centre. Pure strategy.',
    ideas: [
      'The point of ...Bb4 is control of e4. Every white plan revolves around getting that square anyway.',
      'Black happily trades the dark-squared bishop for a knight — unusual, and justified by the doubled pawns or the e4 control it buys.',
      'Three main White systems: 4.Qc2 (Classical, avoids doubled pawns), 4.e3 (Rubinstein), and 4.Nf3.',
      'The Nimzo pairs perfectly with the Queen\'s Indian (...b6) and the Bogo-Indian as a complete 1.d4 repertoire.',
    ],
    plans: { you: ['Fight for e4 with ...d5, ...b6 and ...Bb7, or ...Ne4.', 'Give White doubled c-pawns and target them later.', 'Play ...c5 to open the position once development is complete.'], them: ['Recapture on c3 with the queen to avoid doubled pawns.', 'Build the centre with e4 once the pin is resolved.', 'Use the two bishops in an open position.'] },
    steps: [
      { upto: 4, title: '1.d4 Nf6 2.c4 e6', body: 'Flexible development. Black keeps both the Nimzo-Indian and the Queen\'s Gambit Declined available.' },
      { upto: 6, title: '3.Nc3 Bb4! — the Nimzo', body: 'The pin means White cannot play e4. That single restriction is worth an entire opening.' },
      { upto: 8, title: '4.Qc2 O-O — the Classical Variation', body: 'White protects against doubled pawns in advance by preparing to recapture on c3 with the queen. Black just castles.' },
      { upto: 12, title: '5.a3 Bxc3+ 6.Qxc3 b6', body: 'White gets the two bishops with a clean structure; Black gets a solid position and prepares ...Bb7 and ...d6 or ...d5 to fight for e4.' },
    ],
    branches: [
      { name: 'Rubinstein (4.e3)', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'e3', 'O-O', 'Bd3', 'd5', 'Nf3', 'c5'], idea: 'The most popular line. Black plays ...d5 and ...c5 for a typical isolated-pawn or hanging-pawns middlegame.' },
      { name: 'Sämisch (4.a3)', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nc3', 'Bb4', 'a3', 'Bxc3+', 'bxc3', 'c5'], idea: 'White takes doubled pawns in exchange for the two bishops and a big centre. Black must hit c4 and d4 hard.' },
      { name: 'Bogo-Indian', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'Bb4+'], idea: 'When White plays 3.Nf3 there is no knight on c3 to pin, so the bishop checks instead. A solid, low-theory companion to the Nimzo.' },
    ],
    traps: [],
  },
  {
    id: 'kings-indian',
    name: "King's Indian Defence",
    eco: 'E97',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'Nf3', 'O-O', 'Be2', 'e5', 'O-O', 'Nc6', 'd5', 'Ne7'],
    difficulty: 3,
    style: ['attacking', 'unbalanced', 'ambitious'],
    summary:
      'Let White take the whole centre, castle, then launch everything at the white king with ...f5 and ...g4. The most uncompromising way to play for a win with Black against 1.d4.',
    ideas: [
      'Black gives up the centre on purpose, then attacks it — or ignores it and goes for the king.',
      'The Mar del Plata structure (after d5) is the defining King\'s Indian position: White attacks on the queenside with c5, Black attacks on the kingside with ...f5.',
      'The g7-bishop may be blocked for twenty moves and then decide the game in one.',
      'It is a race. Whoever\'s attack lands first wins — so do not defend when you should be attacking.',
    ],
    plans: { you: ['Play ...Ne7, ...Nd7, ...f5 and pile pawns and pieces at the white king.', 'Play ...g4 and ...Ng6-f4 to jam the kingside.', 'Never open the centre — your play is on the wing.'], them: ['Play c5 and b4 to break through on the queenside.', 'Use Ne1-d3 and f3 to hold back the ...f5 push.', 'Trade off Black\'s attacking pieces.'] },
    steps: [
      { upto: 6, title: '1.d4 Nf6 2.c4 g6 3.Nc3 Bg7', body: 'Black fianchettoes and invites White to build the biggest centre possible.' },
      { upto: 10, title: '4.e4 d6 5.Nf3 O-O', body: 'White accepts the invitation. Black castles — always the priority before counterattacking.' },
      { upto: 12, title: '6.Be2 e5! — the classical strike', body: 'Black challenges the centre. White must decide: close with d5, trade with dxe5, or hold with d4.' },
      { upto: 16, title: '7.O-O Nc6 8.d5 Ne7 — Mar del Plata', body: 'The centre is closed, so both sides attack on opposite wings. Black plays ...Nd7, ...f5, ...g4, ...Ng6 and ...Nf4. White plays c5 and b4. Pure racing.' },
    ],
    branches: [
      { name: 'Sämisch King\'s Indian', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f3', 'O-O', 'Be3', 'e5'], idea: 'White plays f3 to stop ...Ng4 and ...f5 before castling long. Black should hit back with ...c6 and ...b5 on the queenside instead.' },
      { name: 'Fianchetto Variation', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nf3', 'Bg7', 'g3', 'O-O', 'Bg2', 'd6', 'O-O', 'Nc6'], idea: 'White fianchettoes too, which blunts the g7-bishop. A much more positional game where ...Nc6 and ...e5 or ...a6 and ...e5 are the plans.' },
      { name: 'Four Pawns Attack', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'Bg7', 'e4', 'd6', 'f4', 'O-O', 'Nf3', 'c5'], idea: 'White grabs everything. Strike immediately with ...c5 — the centre is overextended and will crack.' },
    ],
    traps: [],
  },
  {
    id: 'grunfeld',
    name: 'Grünfeld Defence',
    eco: 'D85',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7', 'Nf3', 'c5'],
    difficulty: 3,
    style: ['dynamic', 'hypermodern', 'sharp'],
    summary:
      'Let White build a huge centre, then demolish it with pieces and pawns from the flank. Black\'s whole game is directed at d4 and c3. Dynamic, precise, and beloved by attacking players.',
    ideas: [
      'The g7-bishop and the ...c5 pawn attack d4 together. That is the Grünfeld in one sentence.',
      'White\'s big centre is impressive on move seven and fragile on move seventeen.',
      'Black usually trades on c3 to leave White with a doubled pawn and a target.',
      'Needs precision: one slow move and the centre steamrolls you. Learn the lines properly.',
    ],
    plans: { you: ['Hit d4 with ...c5, ...Bg7, ...Qa5 and ...Rd8.', 'Trade pieces to expose the weakened c3 pawn.', 'Use the long diagonal — never block it.'], them: ['Hold the centre with Be3, Rc1 and Qd2.', 'Push d5 or e5 to gain space and shut out the g7-bishop.', 'Play Bc4 and Ne2 with a compact, well-defended pawn front.'] },
    steps: [
      { upto: 4, title: '1.d4 Nf6 2.c4 g6', body: 'A fianchetto start, keeping both the Grünfeld and the King\'s Indian available.' },
      { upto: 6, title: '3.Nc3 d5! — the Grünfeld', body: 'The defining difference from the King\'s Indian: Black challenges the centre immediately with a pawn rather than waiting.' },
      { upto: 10, title: '4.cxd5 Nxd5 5.e4 Nxc3', body: 'White drives the knight away and builds the centre. Black trades it off to damage the queenside pawns.' },
      { upto: 14, title: '6.bxc3 Bg7 7.Nf3 c5 — the Exchange Variation', body: 'Now the plan is obvious: the bishop and the c-pawn both hit d4. Continue with ...O-O, ...Qa5, ...Rd8 and ...Bg4 to pile on.' },
    ],
    branches: [
      { name: 'Russian System', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'Nf3', 'Bg7', 'Qb3', 'dxc4', 'Qxc4', 'O-O'], idea: 'White develops and recaptures on c4 with the queen. Black gets fast play with ...c6, ...b5 or ...Na6 and ...c5.' },
      { name: 'Exchange with 7.Bc4', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nc3', 'd5', 'cxd5', 'Nxd5', 'e4', 'Nxc3', 'bxc3', 'Bg7', 'Bc4', 'c5'], idea: 'The classical main line. Black must play ...c5 and ...Qa5 with precision, but the position is fully sound.' },
      { name: 'Fianchetto Grünfeld', moves: ['d4', 'Nf6', 'c4', 'g6', 'Nf3', 'Bg7', 'g3', 'd5', 'Bg2', 'O-O'], idea: 'A calmer line where White fianchettoes too. Positional, with a fight over the c4 and d5 squares.' },
    ],
    traps: [],
  },
  {
    id: 'slav',
    name: 'Slav Defence',
    eco: 'D15',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'dxc4', 'a4', 'Bf5', 'e3', 'e6', 'Bxc4', 'Bb4'],
    difficulty: 2,
    style: ['solid', 'classical'],
    summary:
      'Support ...d5 with the c-pawn rather than the e-pawn, so the light-squared bishop stays free. The soundest classical answer to the Queen\'s Gambit, and much less claustrophobic than the QGD.',
    ideas: [
      'The whole point of ...c6 instead of ...e6 is that the c8-bishop can develop to f5 or g4.',
      'Taking on c4 and then holding it with ...b5 is the Semi-Slav / Botvinnik territory — sharp and complicated.',
      'a4 is White\'s standard move to prevent ...b5, at the cost of weakening b4.',
      'Black usually ends up with a rock-solid structure and a completely healthy position.',
    ],
    plans: { you: ['Develop the light-squared bishop to f5 before playing ...e6.', 'Occupy b4 once White has committed to a4.', 'Play ...Nbd7, ...O-O and consider ...e5 or ...c5 to open up.'], them: ['Recover c4 and use the extra centre pawn for space.', 'Play e4 at the right moment for a strong centre.', 'Target the slightly loose black queenside after a4.'] },
    steps: [
      { upto: 4, title: '1.d4 d5 2.c4 c6', body: 'The Slav move order. Compare the QGD (...e6), where the c8-bishop is stuck for ten moves.' },
      { upto: 8, title: '3.Nf3 Nf6 4.Nc3 dxc4', body: 'Black takes the pawn, intending to hold it with ...b5 or give it back with good development.' },
      { upto: 10, title: '5.a4 Bf5', body: 'a4 stops ...b5. Black uses the moment to develop the bishop outside the pawn chain — exactly what the Slav is for.' },
      { upto: 14, title: '6.e3 e6 7.Bxc4 Bb4', body: 'White regains the pawn; Black occupies the square that a4 weakened. A completely balanced, very sound position.' },
    ],
    branches: [
      { name: 'Semi-Slav (Meran)', moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'e6', 'e3', 'Nbd7', 'Bd3', 'dxc4', 'Bxc4', 'b5'], idea: 'Black plays both ...c6 and ...e6, accepting a blocked bishop for extra solidity and a strong ...c5 break. Very sharp.' },
      { name: 'Exchange Slav', moves: ['d4', 'd5', 'c4', 'c6', 'cxd5', 'cxd5', 'Nc3', 'Nf6', 'Nf3', 'Nc6'], idea: 'Symmetrical and solid. A good line for White to steer toward a draw, and easy for Black to equalise in.' },
      { name: 'Chebanenko (...a6)', moves: ['d4', 'd5', 'c4', 'c6', 'Nf3', 'Nf6', 'Nc3', 'a6'], idea: 'A modern, flexible system. ...a6 prepares ...b5 in every line and keeps White guessing.' },
    ],
    traps: [],
  },
  {
    id: 'qgd',
    name: "Queen's Gambit Declined",
    eco: 'D35',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'cxd5', 'exd5', 'Bg5', 'Be7', 'e3', 'O-O', 'Bd3', 'Nbd7'],
    difficulty: 2,
    style: ['solid', 'classical', 'reliable'],
    summary:
      'The most respectable way to meet the Queen\'s Gambit. Build an unbreakable wall in the centre and accept a slightly passive position. If you want to never lose in the opening, this is the choice.',
    ideas: [
      'Black\'s structure is extremely hard to attack. The cost is the c8-bishop, which needs a plan.',
      'The standard freeing moves are ...c5 and ...e5. Achieving either usually means full equality.',
      'In the Carlsbad structure, expect White\'s minority attack (b4-b5). Counter with kingside play or ...Ne4.',
      'Solving the light-squared bishop: ...b6 and ...Bb7, or ...Nf6-e8 and ...Bd7-e8-g6 in slower lines.',
    ],
    plans: { you: ['Aim for ...c5 or ...e5 to free the position.', 'Meet the minority attack with ...Ne4 and kingside activity.', 'Re-route the c8-bishop deliberately — do not leave it stranded.'], them: ['Play the minority attack: b4, b5 and pressure on c6.', 'Trade the dark-squared bishop for the f6-knight.', 'Use the extra space to manoeuvre.'] },
    steps: [
      { upto: 4, title: '1.d4 d5 2.c4 e6', body: 'Declining the gambit by supporting d5 with the e-pawn. Solid, but it shuts in the c8-bishop — the defining trade-off of the QGD.' },
      { upto: 8, title: '3.Nc3 Nf6 4.cxd5 exd5', body: 'The Exchange Variation. The Carlsbad structure appears: Black has pawns on a7,b7,c7,d5; White on a2,b2,d4,e3.' },
      { upto: 12, title: '5.Bg5 Be7 6.e3 O-O', body: 'White pins the knight; Black simply breaks the pin and castles. Everything is natural.' },
      { upto: 14, title: '7.Bd3 Nbd7', body: 'Black completes development. Now ...Re8, ...Nf8 and ...Be6 or ...c6 and ...Ne4 — with a very hard position to crack.' },
    ],
    branches: [
      { name: 'Tartakower Variation', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'Be7', 'Bg5', 'h6', 'Bh4', 'O-O', 'e3', 'b6'], idea: 'The cleanest solution to the bad-bishop problem: ...b6 and ...Bb7 gets it onto the long diagonal. A main line at the very top level.' },
      { name: 'Cambridge Springs', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'c6', 'Bg5', 'Nbd7', 'e3', 'Qa5'], idea: 'An active, tricky system where ...Qa5 and ...Bb4 create real threats against the pinned c3-knight.' },
      { name: 'Ragozin', moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Nf3', 'Bb4'], idea: 'A Nimzo-Indian/QGD hybrid: the bishop comes out actively instead of sitting on e7. Sharper and more fun.' },
    ],
    traps: [],
  },
  {
    id: 'dutch-leningrad',
    name: 'Dutch Defence: Leningrad',
    eco: 'A87',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'g6', 'Nf3', 'Bg7', 'O-O', 'O-O', 'c4', 'd6', 'Nc3', 'c6'],
    difficulty: 3,
    style: ['aggressive', 'unbalanced', 'risky'],
    summary:
      'Answer 1.d4 with ...f5 and play for a kingside attack from move one. The Leningrad adds a King\'s-Indian-style fianchetto. Unbalanced and dangerous — for both players.',
    ideas: [
      '...f5 grabs kingside space and prepares ...e5 or ...f4. It also weakens the e6 square and the king permanently.',
      'The Leningrad combines the Dutch pawn on f5 with the King\'s Indian bishop on g7 — double-barrelled kingside pressure.',
      'The ...e5 break is Black\'s main objective. Once achieved, Black is usually doing well.',
      'Watch for early tricks: 2.Bg5, 2.e4 (Staunton Gambit) and 2.Qd3 all need a prepared answer.',
    ],
    plans: { you: ['Play ...Qe8 and ...e5 to open the position in your favour.', 'Advance ...f4 to jam the kingside and open the g7-bishop.', 'Use the half-open f-file with ...Rf7 and doubling.'], them: ['Target e6 and the weakened light squares.', 'Play b4 and c5 for queenside space.', 'Open the centre with e4 to expose the black king.'] },
    steps: [
      { upto: 2, title: '1.d4 f5!?', body: 'The Dutch. Aggressive and committal: kingside space in exchange for a permanently loosened king.' },
      { upto: 6, title: '2.g3 Nf6 3.Bg2 g6', body: 'White fianchettoes to exploit the light squares; Black fianchettoes right back, entering the Leningrad.' },
      { upto: 10, title: '4.Nf3 Bg7 5.O-O O-O', body: 'Both kings are safe. The g7-bishop and the f5 pawn both point at White\'s position.' },
      { upto: 14, title: '6.c4 d6 7.Nc3 c6', body: 'Black prepares ...Qc7 or ...Qe8 followed by ...e5, the central break that justifies the whole opening.' },
    ],
    branches: [
      { name: 'Classical Dutch', moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'e6', 'Nf3', 'Be7', 'O-O', 'O-O', 'c4', 'd6'], idea: 'The old main line with ...e6 and ...d6 instead of the fianchetto. Solid, with the ...e5 break still the main goal.' },
      { name: 'Stonewall Dutch', moves: ['d4', 'f5', 'g3', 'Nf6', 'Bg2', 'e6', 'Nf3', 'd5', 'O-O', 'Bd6', 'c4', 'c6'], idea: 'Pawns on c6, d5, e6, f5 form an immovable wall. The e4 square is a hole but the kingside attack is fast and the plans repeat every game.' },
      { name: 'Staunton Gambit', moves: ['d4', 'f5', 'e4', 'fxe4', 'Nc3', 'Nf6', 'f3'], idea: 'White sacrifices a pawn to blow the centre open before Black is developed. Know 4...d5! and you are fine.' },
    ],
    traps: [],
  },
  {
    id: 'benoni',
    name: 'Modern Benoni',
    eco: 'A61',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6', 'Nf3', 'Bg7', 'Be2', 'O-O'],
    difficulty: 3,
    style: ['sharp', 'asymmetric', 'fighting'],
    summary:
      'Accept a cramped position and a pawn majority on the queenside, then generate counterplay with ...b5 and ...Re8/...c4. Deeply unbalanced, which is exactly why Fischer and Kasparov used it to win.',
    ideas: [
      'Black\'s structure gives a queenside pawn majority and the half-open e-file — two real long-term assets.',
      'The ...b5 break is Black\'s main plan; the ...f5 break is the secondary one.',
      'White\'s dream is e4-e5, breaking through in the centre before Black is organised. Stopping it is priority one.',
      'The Taimanov Attack (7.f4 and 8.Bb5+) is the most dangerous line and must be prepared specifically.',
    ],
    plans: { you: ['Play ...a6, ...Re8 and ...b5 to mobilise the queenside majority.', 'Use the g7-bishop and the e-file against e4 and d5.', 'Consider ...Nbd7-e5 or ...Nh5 to hit White\'s centre.'], them: ['Push e5 to break open the centre.', 'Play f4 and e5 with a direct attack.', 'Blockade the queenside with a4 and Bd3.'] },
    steps: [
      { upto: 4, title: '1.d4 Nf6 2.c4 c5', body: 'Black immediately challenges the centre from the side, inviting White to push past.' },
      { upto: 8, title: '3.d5 e6 4.Nc3 exd5', body: 'White advances and Black undermines. The pawn trade defines the Benoni structure.' },
      { upto: 12, title: '5.cxd5 d6 6.e4 g6', body: 'The characteristic Benoni position: White has a big centre and more space; Black has the queenside majority and the e-file.' },
      { upto: 16, title: '7.Nf3 Bg7 8.Be2 O-O', body: 'Both sides are developed. Black now plays ...a6, ...Re8 and ...Nbd7, preparing ...b5. It is a genuine race between White\'s e5 and Black\'s ...b5.' },
    ],
    branches: [
      { name: 'Taimanov Attack', moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'e4', 'g6', 'f4', 'Bg7', 'Bb5+'], idea: 'White\'s most testing line: f4 and a check on b5 to disrupt Black\'s development. Requires specific preparation — 8...Nfd7 is the main answer.' },
      { name: 'Fianchetto Benoni', moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'e6', 'Nc3', 'exd5', 'cxd5', 'd6', 'Nf3', 'g6', 'g3', 'Bg7', 'Bg2', 'O-O'], idea: 'A calmer, positional line. Black plays ...a6, ...Nbd7 and ...Re8 with a slow build-up.' },
      { name: 'Benko Gambit', moves: ['d4', 'Nf6', 'c4', 'c5', 'd5', 'b5'], idea: 'A pawn sacrifice for permanent pressure on the a- and b-files. Remarkably sound, and the positions are easy to play with Black.' },
    ],
    traps: [],
  },
  {
    id: 'queens-indian',
    name: "Queen's Indian Defence",
    eco: 'E15',
    side: 'b',
    group: 'vs-d4',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Ba6', 'b3', 'Bb4+', 'Bd2', 'Be7'],
    difficulty: 2,
    style: ['positional', 'solid', 'flexible'],
    summary:
      'Fight for e4 with the light-squared bishop on the long diagonal instead of a pin. The natural partner to the Nimzo-Indian: play the Nimzo against 3.Nc3 and the Queen\'s Indian against 3.Nf3.',
    ideas: [
      'Control of e4 is once again the theme, this time from b7 or a6 rather than by pinning a knight.',
      '...Ba6 is the modern move: it hits c4 directly and provokes b3 or Qc2, both of which have drawbacks.',
      'Extremely low risk. Black rarely gets attacked and rarely loses quickly.',
      'Combined with the Nimzo-Indian it covers everything after 1.d4 Nf6 2.c4 e6 with two related systems.',
    ],
    plans: { you: ['Contest e4 with ...Bb7, ...Ne4 and ...d5 or ...c5.', 'Provoke weaknesses with ...Ba6 pressure on c4.', 'Complete development and play a solid, manoeuvring middlegame.'], them: ['Defend c4 with b3 or Qc2 and then build the centre with e4.', 'Fianchetto with g3 and Bg2 to fight for the long diagonal.', 'Use the extra centre pawn for a space advantage.'] },
    steps: [
      { upto: 4, title: '1.d4 Nf6 2.c4 e6', body: 'The standard flexible start, keeping the Nimzo-Indian and the Queen\'s Indian both available.' },
      { upto: 6, title: '3.Nf3 b6', body: 'Since there is no knight on c3 to pin, Black fights for e4 by fianchettoing instead.' },
      { upto: 8, title: '4.g3 Ba6!', body: 'The modern main line. Rather than the automatic ...Bb7, the bishop attacks c4 at once, forcing White to commit.' },
      { upto: 12, title: '5.b3 Bb4+ 6.Bd2 Be7', body: 'The check provokes Bd2, slightly awkward for White, before the bishop settles on e7. Black is solid with easy development and a clear plan of ...d5 or ...c5.' },
    ],
    branches: [
      { name: 'Classical ...Bb7', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'g3', 'Bb7', 'Bg2', 'Be7', 'O-O', 'O-O'], idea: 'The older, simpler treatment. Both bishops face off on the long diagonal and the game is very balanced.' },
      { name: 'Petrosian System', moves: ['d4', 'Nf6', 'c4', 'e6', 'Nf3', 'b6', 'a3', 'Bb7', 'Nc3', 'd5'], idea: 'White plays a3 to prepare Nc3 without allowing ...Bb4. Black responds with ...d5 for a QGD-style position.' },
    ],
    traps: [],
  },
];
