import type { Opening } from './types';

export const WHITE_OPENINGS: Opening[] = [
  {
    id: 'italian',
    name: 'Italian Game',
    eco: 'C50',
    side: 'w',
    group: 'e4',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'c3', 'Nf6', 'd3', 'd6', 'O-O', 'O-O'],
    difficulty: 1,
    style: ['classical', 'flexible'],
    summary:
      'The most natural way to start a chess game: occupy the centre, develop a knight, point a bishop at f7. Nothing is forced, so you get to play chess rather than recite theory.',
    ideas: [
      'The bishop on c4 eyes f7 — the only square in the black camp defended by the king alone.',
      'c3 and d3 build a broad pawn centre slowly. The threat of d3-d4 hangs over the position for the whole middlegame.',
      'Nb1-d2-f1-g3 is the standard regrouping: the knight takes four moves to reach a great square, and it is worth every tempo.',
      'Do not rush h3. Play it when Black actually threatens ...Bg4, not before.',
    ],
    plans: {
      you: [
        'Complete development, castle, then re-route the b1-knight to g3 or e3.',
        'Prepare d3-d4 when Black cannot meet it with a comfortable ...exd4.',
        'If Black castles kingside and you have a knight on g3, consider a slow kingside build-up with Nh4 and f4.',
      ],
      them: [
        'Black mirrors your setup and aims for ...d5 to free the position.',
        'Black may play ...a6 and ...Ba7 to keep the bishop when you push d4.',
        'The ...Na5 manoeuvre trades off your good light-squared bishop.',
      ],
    },
    steps: [
      { upto: 2, title: '1.e4 e5 — the classical centre', body: 'Both sides stake a claim in the middle. The e5 pawn is defended only by the queen, which is why 2.Nf3 comes with a real threat.' },
      { upto: 4, title: '2.Nf3 Nc6 — attack and defend', body: 'Nf3 hits e5 and develops toward the centre. Nc6 is the only developing move that defends the pawn, which is why it is played almost universally.' },
      { upto: 6, title: '3.Bc4 Bc5 — the Giuoco Piano', body: 'Your bishop takes the a2-g8 diagonal and stares at f7. Black copies. "Giuoco Piano" means "quiet game" — the fight is about who can improve their position faster.' },
      { upto: 8, title: '4.c3 Nf6 — building slowly', body: 'c3 prepares d4 and gives the c4-bishop a retreat on c2 later. Black develops with tempo-free ...Nf6, eyeing your e4 pawn.' },
      { upto: 10, title: '5.d3 d6 — the Pianissimo', body: 'd3 supports e4 and keeps the position closed. This is the modern main line: players from club level to world championship use it because the plans are rich and the theory is light.' },
      { upto: 12, title: '6.O-O O-O — king safety first', body: 'Castle, then start the Nb1-d2-f1-g3 journey. You have a solid position with no weaknesses and a clear plan. That is all an opening needs to do.' },
    ],
    branches: [
      { name: 'Evans Gambit', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Bc5', 'b4'], idea: 'Sacrifice a wing pawn to gain time for c3 and d4, building a huge centre. Sharp and fun, and still respected.' },
      { name: 'Two Knights Defence', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6'], idea: 'Black ignores f7 and counterattacks e4. This invites 4.Ng5, the most forcing try in the whole opening.' },
      { name: 'Hungarian Defence', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Be7'], idea: 'A passive but solid way for Black to sidestep all the theory. Take space with d4 and enjoy a pleasant game.' },
    ],
    traps: [
      {
        name: "Légal's Mate",
        moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'd6', 'Nc3', 'Bg4', 'h3', 'Bh5', 'Nxe5', 'Bxd1', 'Bxf7+', 'Ke7', 'Nd5#'],
        explain:
          'White gives up the queen because the pinned knight was never really pinned — after 6.Nxe5 Bxd1, the two bishops and the knight deliver mate. If Black instead takes on e5, White simply wins the piece back with Qxh5.',
      },
      {
        name: 'Fried Liver Attack',
        moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bc4', 'Nf6', 'Ng5', 'd5', 'exd5', 'Nxd5', 'Nxf7', 'Kxf7', 'Qf3+', 'Ke6', 'Nc3'],
        explain:
          'The knight sacrifice drags the black king to e6 where it is hunted by every white piece. Black is objectively holding on with precise defence, but at club level this scores enormously well. Note that 5...Na5! is the correct answer, not 5...Nxd5.',
      },
    ],
  },
  {
    id: 'ruy-lopez',
    name: 'Ruy López',
    eco: 'C84',
    side: 'w',
    group: 'e4',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'd6', 'c3', 'O-O'],
    difficulty: 3,
    style: ['classical', 'positional', 'deep'],
    summary:
      'The most respected opening in chess. White pressures the knight that defends e5, then spends fifteen moves manoeuvring for a kingside attack or a queenside bind. Rich, difficult, and rewarding.',
    ideas: [
      'Bb5 is not a real pin — the d7 pawn blocks the line to the king. It is pressure on the defender of e5, not a pin.',
      'The whole opening revolves around whether White can ever profitably play Bxc6 and win the e5 pawn.',
      'c3 and d4 is the standard central break, supported by the bishop on the a2-g8 diagonal.',
      "Nb1-d2-f1-g3 again — the same manoeuvre as the Italian, and the reason both openings feel related.",
    ],
    plans: {
      you: [
        'Build the centre with c3 and d4, then decide between d4-d5 (space) and dxe5 (open lines).',
        'Re-route the queen knight to g3 or e3 and add pieces to the kingside.',
        'In the Exchange Variation, trade on c6 and play for the pure pawn-structure endgame.',
      ],
      them: [
        "Black plays ...a6 and ...b5 to kick the bishop and gain queenside space.",
        'The Marshall Attack (...d5!?) sacrifices a pawn for a ferocious kingside initiative.',
        'The Breyer and Chigorin systems re-route the knight to build a solid fortress.',
      ],
    },
    steps: [
      { upto: 4, title: '1.e4 e5 2.Nf3 Nc6', body: 'The same start as the Italian. Everything so far is forced by common sense.' },
      { upto: 5, title: '3.Bb5 — the Spanish bishop', body: 'White attacks the defender of e5. The immediate 4.Bxc6 dxc6 5.Nxe5 fails to 5...Qd4 forking knight and pawn — worth playing through once so you understand why the threat is slow, not instant.' },
      { upto: 8, title: '3...a6 4.Ba4 Nf6 — the Morphy Defence', body: 'Black asks the bishop to commit. Retreating to a4 keeps the pressure. Now ...b5 is always available to Black, which shapes the whole middlegame.' },
      { upto: 10, title: '5.O-O Be7', body: 'White casually ignores the e4 pawn. After 5...Nxe4 6.d4 White regains it with a strong centre — the Open Spanish, a respectable line in its own right.' },
      { upto: 12, title: '6.Re1 b5 7.Bb3', body: 'Re1 defends e4 properly and renews the threat on e5. Black finally kicks the bishop, which settles on b3 where it will sit for the next twenty moves.' },
      { upto: 16, title: '7...d6 8.c3 O-O — the Closed Spanish', body: 'Both sides are fully developed. White will play h3 and d4; Black will pick a knight re-route. This is where chess actually begins.' },
    ],
    branches: [
      { name: 'Berlin Defence', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'Nf6'], idea: 'The "Berlin Wall". After 4.O-O Nxe4 5.d4 Nd6 6.Bxc6 dxc6 7.dxe5 Nf5 8.Qxd8+ Kxd8 the queens come off and Black has a famously solid, if slightly passive, endgame.' },
      { name: 'Exchange Variation', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Bxc6', 'dxc6'], idea: 'Trade immediately and head for an endgame where your 4-vs-3 kingside majority can make a passed pawn and Black\'s doubled c-pawns cannot. Low theory, real winning chances.' },
      { name: 'Marshall Attack', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'Nf6', 'O-O', 'Be7', 'Re1', 'b5', 'Bb3', 'O-O', 'c3', 'd5'], idea: 'Black gives a pawn for a lasting attack. If you would rather not memorise the antidote, play 8.a4 (an Anti-Marshall) instead of 8.c3.' },
    ],
    traps: [
      {
        name: "Noah's Ark Trap",
        moves: ['e4', 'e5', 'Nf3', 'Nc6', 'Bb5', 'a6', 'Ba4', 'd6', 'd4', 'b5', 'Bb3', 'Nxd4', 'Nxd4', 'exd4', 'Qxd4', 'c5', 'Qd5', 'Be6', 'Qc6+', 'Bd7', 'Qd5', 'c4'],
        explain:
          'Black\'s queenside pawns roll forward and the b3-bishop runs out of squares — it is trapped by pawns, like an ark closing in. The lesson generalises: a bishop on b3 facing ...a6, ...b5 and ...c4 is always in danger.',
      },
    ],
  },
  {
    id: 'scotch',
    name: 'Scotch Game',
    eco: 'C45',
    side: 'w',
    group: 'e4',
    moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Bc5', 'Be3', 'Qf6', 'c3', 'Nge7'],
    difficulty: 2,
    style: ['open', 'direct'],
    summary:
      'Open the centre on move three. You trade the theory-heavy Ruy López for a concrete, piece-driven game where knowing a handful of ideas beats knowing nothing at all.',
    ideas: [
      'Playing d4 immediately means you never have to learn the Ruy López or face the Berlin.',
      'The knight on d4 is well placed but a target: ...Bc5 and ...Qf6 both hit it.',
      'Be3 defends the knight and prepares to meet ...Bxd4 with cxd4, giving you a strong pawn centre.',
      'White usually ends up with the two bishops or a space advantage; Black gets quick development.',
    ],
    plans: {
      you: ['Support d4 with Be3 and c3.', 'Castle and push f4 or trade into a favourable structure.', 'In the 4...Nf6 5.Nxc6 line, play e5 to gain space and harass the f6-knight.'],
      them: ['Pressure the d4-knight with ...Bc5 and ...Qf6.', 'Play ...Nge7 and ...d5 to free the position.', 'Trade pieces to reach a comfortable endgame.'],
    },
    steps: [
      { upto: 4, title: '1.e4 e5 2.Nf3 Nc6', body: 'Standard opening moves — the same crossroads as the Italian and the Ruy López.' },
      { upto: 6, title: '3.d4! exd4', body: 'You strike in the centre. Black essentially has to take, because defending e5 with ...d6 leaves the position cramped after dxe5.' },
      { upto: 8, title: '4.Nxd4 Bc5', body: 'Recapturing with the knight centralises it. Black immediately attacks it along the a7-g1 diagonal.' },
      { upto: 10, title: '5.Be3 Qf6', body: 'Be3 shores up the knight. Black piles on with the queen. Do not panic — you have a concrete answer.' },
      { upto: 12, title: '6.c3 Nge7', body: 'c3 adds a third defender. If Black ever takes on d4 you recapture with the c-pawn and own a beautiful centre. Next: Bc4, O-O, and Nd2-f3.' },
    ],
    branches: [
      { name: 'Scotch, 4...Nf6', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Nf6'], idea: 'Play 5.Nxc6 bxc6 6.e5, kicking the knight and gaining space. The doubled c-pawns give you a long-term target.' },
      { name: 'Göring Gambit', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'c3'], idea: 'Offer a pawn (or two) for rapid development and open lines toward f7. Excellent at fast time controls.' },
      { name: 'Steinitz Variation', moves: ['e4', 'e5', 'Nf3', 'Nc6', 'd4', 'exd4', 'Nxd4', 'Qh4'], idea: 'An aggressive queen sortie hitting e4. Meet it with 5.Nc3 (or 5.Nb5) — the queen will cost Black time.' },
    ],
    traps: [],
  },
  {
    id: 'vienna',
    name: 'Vienna Game',
    eco: 'C25',
    side: 'w',
    group: 'e4',
    moves: ['e4', 'e5', 'Nc3', 'Nf6', 'f4', 'd5', 'fxe5', 'Nxe4', 'Nf3', 'Be7', 'd4', 'O-O'],
    difficulty: 2,
    style: ['aggressive', 'gambit'],
    summary:
      "A King's Gambit with the knight developed first, so it is far safer. You get an early f4 break and attacking chances without the usual risk.",
    ideas: [
      'Nc3 first means you never face the King\'s Gambit Declined problems — the f4 push comes with support.',
      'After 3.f4 d5 the position opens quickly; know the first six moves and you will be better prepared than most opponents.',
      'The e5 pawn cramps Black and supports a knight landing on d4 or g5.',
      "Against 2...Nc6, 3.Bc4 invites the Frankenstein-Dracula; against 2...Bc5, 3.Qg4!? is an immediate test.",
    ],
    plans: { you: ['Push f4 and open the f-file for the rook.', 'Castle kingside and aim pieces at f7 and h7.', 'Use the e5 wedge to restrict Black\'s knight.'], them: ['Counter in the centre with ...d5.', 'Trade pieces to blunt the attack.', 'Target the weakened e1-h4 diagonal after f4.'] },
    steps: [
      { upto: 2, title: '1.e4 e5', body: 'The usual start.' },
      { upto: 4, title: '2.Nc3 Nf6', body: 'A quiet-looking developing move that actually prepares an aggressive f4. Black develops naturally and hits e4.' },
      { upto: 6, title: '3.f4! d5', body: 'The Vienna Gambit. Black\'s best is the central counter ...d5 — anything else and you get a free attack after fxe5.' },
      { upto: 8, title: '4.fxe5 Nxe4', body: 'Material stays level but the position is sharp. Black\'s knight is active but loose.' },
      { upto: 12, title: '5.Nf3 Be7 6.d4 O-O', body: 'You have a big pawn centre and the half-open f-file. Bd3, O-O and Qe1-h4 is the attacking scheme.' },
    ],
    branches: [
      { name: 'Vienna, quiet 3.Bc4', moves: ['e4', 'e5', 'Nc3', 'Nf6', 'Bc4'], idea: 'A calmer move order that keeps f4 in reserve. Careful: 3...Nxe4! is the critical reply and leads to wild play.' },
      { name: 'Vienna vs 2...Nc6', moves: ['e4', 'e5', 'Nc3', 'Nc6', 'f4'], idea: 'The gambit still works. After 3...exf4 4.Nf3 you have a King\'s Gambit with an extra developing move.' },
    ],
    traps: [],
  },
  {
    id: 'kings-gambit',
    name: "King's Gambit",
    eco: 'C33',
    side: 'w',
    group: 'e4',
    moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'g5', 'h4', 'g4', 'Ne5'],
    difficulty: 3,
    style: ['romantic', 'gambit', 'sharp'],
    summary:
      'Offer a pawn on move two for the centre and the f-file. Objectively dubious against perfect play, devastating against imperfect play — which is every game you will ever play.',
    ideas: [
      'You trade a pawn for the e5 square, the f-file, and a two-pawn centre after d4.',
      'The cost is real: your king is exposed on the e1-h4 diagonal. ...Qh4+ is always in the air.',
      'The Kieseritzky (5.Ne5) is the main line against the greedy 3...g5.',
      'Know one answer to the King\'s Gambit Declined (2...Bc5) — it is more common than any accepted line at club level.',
    ],
    plans: { you: ['Play d4 to build the centre and open the c1-bishop.', 'Recapture on f4 when convenient and use the f-file.', 'Target f7 with Bc4 and the knight.'], them: ['Hold the extra pawn with ...g5.', 'Check on h4 to disrupt castling.', 'Give the pawn back at the right moment for free development.'] },
    steps: [
      { upto: 2, title: '1.e4 e5', body: 'Black takes the centre.' },
      { upto: 4, title: '2.f4! exf4', body: 'The gambit. Declining with 2...Bc5 is respectable; accepting is the critical test.' },
      { upto: 6, title: '3.Nf3 g5', body: 'Nf3 is essential — it stops ...Qh4+ cold. Black grimly holds the pawn with ...g5.' },
      { upto: 8, title: '4.h4 g4', body: 'You undermine the pawn chain at once. Black must push past.' },
      { upto: 9, title: '5.Ne5 — the Kieseritzky', body: 'The knight leaps to a strong square rather than retreating. White follows with d4, Bxf4 and Nc3, with a massive centre for the pawn.' },
    ],
    branches: [
      { name: "King's Gambit Declined", moves: ['e4', 'e5', 'f4', 'Bc5'], idea: 'Black ignores the pawn and stops you castling comfortably. Play 3.Nf3 d6 4.c3 and build the centre with d4.' },
      { name: 'Falkbeer Counter-Gambit', moves: ['e4', 'e5', 'f4', 'd5'], idea: 'Black counter-gambits in the centre. 3.exd5 e4 is the critical line; 4.d3 is the modern recommendation.' },
      { name: 'Modern Defence', moves: ['e4', 'e5', 'f4', 'exf4', 'Nf3', 'd5'], idea: 'Black returns the pawn for quick development. Take with 4.exd5 and play a normal, pleasant game.' },
    ],
    traps: [],
  },
  {
    id: 'london',
    name: 'London System',
    eco: 'D02',
    side: 'w',
    group: 'd4',
    moves: ['d4', 'd5', 'Bf4', 'Nf6', 'e3', 'e6', 'Nf3', 'c5', 'c3', 'Nc6', 'Nbd2', 'Bd6', 'Bg3', 'O-O', 'Bd3'],
    difficulty: 1,
    style: ['system', 'solid', 'low-theory'],
    summary:
      'A setup you can play against almost anything: Bf4, e3, Nf3, c3, Nbd2, Bd3. Minimal memorisation, maximum reliability — which is why it went from club favourite to world-championship weapon.',
    ideas: [
      'Get the dark-squared bishop outside the pawn chain before playing e3. This is the single most important move-order rule in the London.',
      'The pawn triangle c3-d4-e3 is rock solid. Your pieces have obvious squares behind it.',
      'Ne5 is the key central outpost, usually supported by Nbd2-f3 and f4.',
      'The standard attacking scheme is Ne5, Qf3 or Qe2, and a kingside pawn storm if Black castles short.',
    ],
    plans: { you: ['Occupy e5 with a knight and support it.', 'Trade dark-squared bishops if Black plays ...Bd6, which eases your position.', 'Play for a kingside attack with Qe2, Rae1 and e3-e4.'], them: ['Hit d4 with ...c5 to challenge the centre.', 'Play ...Qb6 pressuring b2 while the bishop sits on f4.', 'Trade off the strong e5 knight.'] },
    steps: [
      { upto: 2, title: '1.d4 d5', body: 'A normal queen\'s-pawn start.' },
      { upto: 4, title: '2.Bf4! Nf6', body: 'The defining move. The bishop escapes before e3 locks it in — this is what separates the London from a passive Colle setup.' },
      { upto: 8, title: '3.e3 e6 4.Nf3 c5', body: 'You complete the triangle. Black immediately challenges d4 with ...c5, the main plan against every London.' },
      { upto: 12, title: '5.c3 Nc6 6.Nbd2 Bd6', body: 'c3 holds the centre. Nbd2 heads for f3 or e4. When Black offers a trade on f4, step back to g3 and keep the bishop.' },
      { upto: 15, title: '7.Bg3 O-O 8.Bd3', body: 'Both bishops are aimed at the black king. Castle, play Ne5, and build with Qf3 and Rae1.' },
    ],
    branches: [
      { name: 'Jobava London', moves: ['d4', 'd5', 'Nc3', 'Nf6', 'Bf4'], idea: 'A sharper cousin: Nc3 before e3 supports an early e4 or Nb5. Far more aggressive, slightly more theory.' },
      { name: 'London vs King\'s Indian setup', moves: ['d4', 'Nf6', 'Bf4', 'g6', 'Nc3', 'd5', 'e3', 'Bg7', 'h4'], idea: 'Against a fianchetto, the h-pawn advance is genuinely dangerous because Black has no light-squared defender.' },
      { name: 'The ...Qb6 test', moves: ['d4', 'd5', 'Bf4', 'Nf6', 'e3', 'c5', 'c3', 'Qb6'], idea: 'Black attacks b2. The calm answer is 5.Qb3, offering a trade that leaves you comfortable.' },
    ],
    traps: [],
  },
  {
    id: 'queens-gambit',
    name: "Queen's Gambit",
    eco: 'D06',
    side: 'w',
    group: 'd4',
    moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'cxd5', 'exd5', 'Bg5', 'c6', 'e3', 'Be7', 'Bd3', 'O-O', 'Qc2'],
    difficulty: 2,
    style: ['classical', 'positional'],
    summary:
      'Not really a gambit — if Black grabs the pawn with ...dxc4, you win it straight back. The point is to trade a wing pawn for a centre pawn and get a lasting spatial edge.',
    ideas: [
      'After 2...dxc4 you play 3.e3 and 4.Bxc4. Black cannot hold the pawn with ...b5 because of a2-a4.',
      'The Exchange Variation (4.cxd5) creates the Carlsbad structure — the home of the minority attack.',
      'Minority attack: push b2-b4-b5 against Black\'s three queenside pawns to create a weakness on c6.',
      'Bg5 pins the f6-knight and makes ...Ne4 or ...c5 harder to arrange.',
    ],
    plans: { you: ['Play the minority attack with b4-b5 in the Carlsbad structure.', 'Or switch plans: castle kingside and push e3-e4 for a central break.', 'Trade the dark-squared bishop for the f6-knight when it helps your structure.'], them: ['Free the position with ...c5 or ...e5.', 'Re-route the light-squared bishop, the classic QGD problem piece.', 'Meet the minority attack with kingside counterplay.'] },
    steps: [
      { upto: 3, title: '1.d4 d5 2.c4 — the offer', body: 'You attack d5 from the side. Black can decline (2...e6, 2...c6) or accept (2...dxc4). Declining is most common.' },
      { upto: 6, title: '2...e6 3.Nc3 Nf6', body: 'The Queen\'s Gambit Declined. Black builds a solid wall but shuts in the c8-bishop — a problem that lasts the whole game.' },
      { upto: 8, title: '4.cxd5 exd5 — the Carlsbad structure', body: 'This exchange defines the middlegame: White has pawns on a2,b2,d4,e3 and Black on a7,b7,c6,d5. Both sides now have a textbook plan.' },
      { upto: 10, title: '5.Bg5 c6', body: 'Bg5 pins the knight. Black solidifies d5 with the c-pawn, entering the structure where the minority attack lives.' },
      { upto: 15, title: '6.e3 Be7 7.Bd3 O-O 8.Qc2', body: 'A perfect setup. Now play Nge2 (not Nf3, keeping the f-pawn free) or go straight for b4-b5 on the queenside.' },
    ],
    branches: [
      { name: "Queen's Gambit Accepted", moves: ['d4', 'd5', 'c4', 'dxc4'], idea: 'Play 3.e3 and 4.Bxc4 to regain the pawn with a fine centre. Black gets a free game but concedes the middle.' },
      { name: 'Slav Defence', moves: ['d4', 'd5', 'c4', 'c6'], idea: 'Black supports d5 with the c-pawn, keeping the c8-bishop free. Solid and popular; meet it with 3.Nf3 Nf6 4.Nc3.' },
      { name: 'Albin Counter-Gambit', moves: ['d4', 'd5', 'c4', 'e5'], idea: 'A pawn sacrifice for a wedge on d4. Take twice and play 4.Nf3 — and know the Lasker Trap before you play 5.e3??.' },
    ],
    traps: [
      {
        name: 'Elephant Trap',
        moves: ['d4', 'd5', 'c4', 'e6', 'Nc3', 'Nf6', 'Bg5', 'Nbd7', 'cxd5', 'exd5', 'Nxd5', 'Nxd5', 'Bxd8', 'Bb4+', 'Qd2', 'Bxd2+', 'Kxd2', 'Kxd8'],
        explain:
          'The d5 pawn looks free because the knight on d7 is "pinned" by the bishop on g5 — it is not. After 6.Nxd5?? Nxd5! 7.Bxd8 Bb4+ Black regains the queen and emerges a piece up. Know it from both sides.',
      },
    ],
  },
  {
    id: 'catalan',
    name: 'Catalan Opening',
    eco: 'E01',
    side: 'w',
    group: 'd4',
    moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'dxc4', 'Qc2', 'a6', 'Qxc4', 'b5'],
    difficulty: 3,
    style: ['positional', 'squeeze'],
    summary:
      'Combine the Queen\'s Gambit with a kingside fianchetto. The bishop on g2 exerts pressure down the long diagonal for the entire game — the most patient, grinding opening in the repertoire.',
    ideas: [
      'The g2-bishop is the soul of the position. Never trade it casually.',
      'Black usually grabs the c4 pawn; you regain it with Qa4, Qc2 or Ne5 while gaining time.',
      'Open Catalan: Black plays ...dxc4 and tries to hold with ...b5. Closed Catalan: Black keeps ...d5 and suffers slowly.',
      'Typical winning method: pressure c6 and b7, trade into an endgame, convert the space edge.',
    ],
    plans: { you: ['Recover c4 with the queen, then push e4 or a4 to break the queenside.', 'Pile on the long diagonal with Qc2, Rd1 and Ne5.', 'Trade the dark-squared bishops to make Black\'s position passive.'], them: ['Hold the extra pawn with ...b5 and ...Bb7.', 'Free the position with ...c5 or ...e5.', 'Trade off the g2-bishop with ...Ba6 or ...Bb7 and ...c6.'] },
    steps: [
      { upto: 4, title: '1.d4 Nf6 2.c4 e6', body: 'A standard Indian start. Black keeps options between the Nimzo-Indian and the Queen\'s Gambit.' },
      { upto: 6, title: '3.g3! d5', body: 'The Catalan move. It also sidesteps the Nimzo-Indian entirely, which is a large part of the appeal.' },
      { upto: 11, title: '4.Bg2 Be7 5.Nf3 O-O 6.O-O', body: 'Both sides complete development. The bishop on g2 stares through d5 at b7 for the rest of the game.' },
      { upto: 16, title: '6...dxc4 7.Qc2 a6 8.Qxc4 b5', body: 'The Open Catalan. You have regained the pawn; Black has queenside space. Now Qc2 or Qb3, followed by a4 to break up the pawn chain.' },
    ],
    branches: [
      { name: 'Closed Catalan', moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'Nbd7'], idea: 'Black holds the centre instead of taking. You get a risk-free space advantage and a long squeeze.' },
      { name: 'Open Catalan with 7.Ne5', moves: ['d4', 'Nf6', 'c4', 'e6', 'g3', 'd5', 'Bg2', 'Be7', 'Nf3', 'O-O', 'O-O', 'dxc4', 'Ne5'], idea: 'An immediate assault on c6 and c4. Sharper than the queen recaptures and leads to forcing play.' },
    ],
    traps: [],
  },
  {
    id: 'english',
    name: 'English Opening',
    eco: 'A20',
    side: 'w',
    group: 'flank',
    moves: ['c4', 'e5', 'Nc3', 'Nf6', 'g3', 'd5', 'cxd5', 'Nxd5', 'Bg2', 'Nb6', 'Nf3', 'Nc6', 'O-O', 'Be7'],
    difficulty: 2,
    style: ['flexible', 'positional'],
    summary:
      'A Sicilian with colours reversed and an extra tempo. You control d5 from the side and keep every central option open — deeply flexible, and it transposes into half the openings in this list.',
    ideas: [
      'After 1.c4 e5 you are effectively playing a Sicilian Dragon as White, a move up.',
      'The g2-bishop and the c-file are your two long-term assets.',
      'Common transpositions: into the Catalan (with d4 and g3), the QGD (with d4 and Nc3), or the Réti.',
      'Against 1...c5 (Symmetrical), take space with d4 or play the flexible 2.Nf3 and 3.g3.',
    ],
    plans: { you: ['Fianchetto, castle, and pressure the centre from the wings.', 'Play d3 and f4 for a reversed-Sicilian kingside expansion.', 'Use the half-open c-file with Rc1 and Nd5.'], them: ['Take central space with ...e5 and ...d5.', 'Mirror your setup with ...c5 and ...g6.', 'Play ...Nb4 or ...Bb4 to disrupt your development.'] },
    steps: [
      { upto: 2, title: '1.c4 e5 — the reversed Sicilian', body: 'Black takes the centre. You will undermine it from the flank, exactly as Black does in a real Sicilian.' },
      { upto: 6, title: '2.Nc3 Nf6 3.g3 d5', body: 'You fianchetto; Black strikes in the centre. This is the critical, principled continuation.' },
      { upto: 10, title: '4.cxd5 Nxd5 5.Bg2 Nb6', body: 'The knight is kicked around but ends up on a decent square. The g2-bishop already bites on the long diagonal.' },
      { upto: 14, title: '6.Nf3 Nc6 7.O-O Be7', body: 'A healthy position with a small pull. Play d3, Be3 or a3, and Rc1 — then decide between b4 and d4.' },
    ],
    branches: [
      { name: 'Symmetrical English', moves: ['c4', 'c5'], idea: 'Black copies. Play 2.Nf3 Nf6 3.g3 and head for a Réti-style structure, or grab space with an early d4.' },
      { name: 'English vs King\'s Indian setup', moves: ['c4', 'Nf6', 'Nc3', 'g6', 'g3', 'Bg7', 'Bg2', 'O-O', 'Nf3'], idea: 'A King\'s Indian where White has not committed to d4 — far less theory and Black\'s usual ...e5 break is less effective.' },
    ],
    traps: [],
  },
  {
    id: 'reti',
    name: 'Réti Opening',
    eco: 'A09',
    side: 'w',
    group: 'flank',
    moves: ['Nf3', 'd5', 'c4', 'e6', 'g3', 'Nf6', 'Bg2', 'Be7', 'O-O', 'O-O', 'd3', 'c5', 'Nbd2'],
    difficulty: 2,
    style: ['hypermodern', 'flexible'],
    summary:
      'Develop first, decide later. You invite Black to build a big centre, then attack it from the flanks with c4, g3 and a timely e4 or d4.',
    ideas: [
      'Hypermodern principle: a pawn centre is only strong if it cannot be attacked.',
      'The Réti transposes freely into the English, the Catalan and the King\'s Indian Attack — flexibility is the whole point.',
      'The g2-bishop plus a c4 push puts constant pressure on d5.',
      'Because you commit nothing early, your opponent rarely gets to use their prepared lines.',
    ],
    plans: { you: ['Fianchetto, castle, then choose a central break with e4 or d4.', 'Play Nbd2 and Rc1 with pressure on the c-file.', 'Switch to a King\'s Indian Attack setup with e4, Re1 and Nf1-g3 if Black plays ...e6 and ...c5.'], them: ['Build and hold the centre with ...d5 and ...c6.', 'Fianchetto in return and fight for the long diagonal.', 'Play ...d4 to gain space and shut the g2-bishop out.'] },
    steps: [
      { upto: 2, title: '1.Nf3 d5', body: 'A flexible first move that avoids all of Black\'s prepared replies to 1.e4 and 1.d4.' },
      { upto: 4, title: '2.c4 e6', body: 'You attack d5 from the flank without committing your own centre pawns.' },
      { upto: 10, title: '3.g3 Nf6 4.Bg2 Be7 5.O-O O-O', body: 'Complete development first. You still have not decided what your centre will look like — that is a genuine advantage.' },
      { upto: 13, title: '6.d3 c5 7.Nbd2', body: 'Now the plan crystallises: e2-e4 next, with a strong King\'s Indian Attack formation against Black\'s French-style centre.' },
    ],
    branches: [
      { name: 'Réti Gambit accepted', moves: ['Nf3', 'd5', 'c4', 'dxc4'], idea: 'Play 3.e3 or 3.Na3 and regain the pawn comfortably while Black has lost time.' },
      { name: 'Advance with ...d4', moves: ['Nf3', 'd5', 'c4', 'd4'], idea: 'Black grabs space. Undermine with 3.b4 or 3.e3 — the pawn on d4 becomes a target, not a strength.' },
    ],
    traps: [],
  },
];
